env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:solid/typescript
  - plugin:@typescript-eslint/recommended
overrides:
  - files: ["*.config.js"]
    env:
      node: true
parserOptions:
  ecmaVersion: latest
  ecmaFeatures:
    tsx: true
  sourceType: module
rules:
  indent:
    - error
    - 2
  quotes:
    - error
    - single
  semi:
    - error
    - always
  simple-import-sort/imports:
    - error
  sort-imports:
    - off
  no-unused-vars:
    - off
  "@typescript-eslint/no-unused-vars":
    - warn
  no-multiple-empty-lines:
    - error
    - max: 1
parser: "@typescript-eslint/parser"
plugins:
  - solid
  - prettier
  - simple-import-sort
