FROM node:19-alpine3.17 AS build

# Install Pnpm
RUN npm install --global pnpm

WORKDIR /app
COPY ./package.json ./
COPY ./pnpm-lock.yaml ./
RUN pnpm install --production
COPY . .
RUN pnpm build

FROM nginx:1.23.3-alpine as prod
COPY ./etc/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
