version: "3.9"

services:
  frontend-dev:
    container_name: frontend-dev
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: base
    profiles:
      - dev
    networks:
      - frontend
    ports:
      - 3000:3000
    command: pnpm dev --host
    volumes:
      - ./frontend:/app:ro
      - /app/node_modules

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    profiles:
      - prod
    networks:
      - frontend
    ports:
      - 80:80
      - 443:443
    restart: always

networks:
  frontend: {}
