version: "3.9"

services:
  frontend-dev:
    container_name: frontend-dev
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: base
    profiles:
      - dev
    networks:
      - frontend
    ports:
      - 3000:3000
    command: pnpm dev --host
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: always

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    profiles:
      - prod
    networks:
      - frontend
    ports:
      - 80:80
      - 443:443
    restart: always

  gateway-dev:
    container_name: backend-dev
    build:
      context: ./backend/gateway
      dockerfile: Dockerfile
      target: base
    profiles:
      - dev
    networks:
      - frontend
      - backend
    ports:
      - 4000:4000
    command: pnpm dev
    volumes:
      - ./backend/gateway:/app
      - /app/node_modules
    restart: always

networks:
  frontend: {}
  backend: {}
