#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /backend
ENTRYPOINT ["dotnet", "watch", "run", "--project", "src/App", "--urls", "http://+:5101"]
