env:
  node: true
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - prettier
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  indent:
    - error
    - 2
  quotes:
    - error
    - single
  semi:
    - error
    - always
  simple-import-sort/imports:
    - error
  sort-imports:
    - off
  no-multiple-empty-lines:
    - error
    - max: 1
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
  - prettier
  - simple-import-sort
